#!/bin/bash
echo "Checking for Updates...."
update=$(curl -H 'Cache-Control: no-cache' -s https://raw.githubusercontent.com/BadGuy552/scripts/master/v | grep installer | awk '{print $2}')
version=12
if [ "$update" -gt "$version" ]
then
echo "Updating Installer..."
wget -q https://raw.githubusercontent.com/BadGuy552/scripts/master/installer
rm /bin/installer 1>/dev/null 2>/dev/null
mv installer /bin/ 1>/dev/null 2>/dev/null
chmod a+x /bin/installer 1>/dev/null 2>/dev/null
echo "Run Script Again!"
exit 1
fi
if [ -d /etc/installer ]
then
echo ""
else
mkdir /etc/installer
fi
menu="\033[41;1;37m"
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0m"

echo -e "$menu""                        Installer                       $fim"
notes=$(curl -s --max-time 2 https://raw.githubusercontent.com/BadGuy552/scripts/master/installernotes.txt)
if [ "$notes" ]
then
echo -e "$cyanClaro""Notes from the Developer:$fim\n""$vermelho""$notes""$fim"
else
echo -e "$cyanClaro""Notes from the Developer:$fim\n""Not Available."
fi
echo -e "$cyanClaro""Getting Scripts List...$fim"
curl -s --max-time 3 https://raw.githubusercontent.com/BadGuy552/scripts/master/scripts.txt > /etc/installer/scripts.txt
scriptslist=$(cat /etc/installer/scripts.txt)
echo -e "$cyanClaro""Scripts to Install:$fim"
echo -e "$vermelho""$(cat /etc/installer/scripts.txt) $fim"
read -p "Insert Script Name to Install: " script

if [ "$script" ]
then
scriptcheck=$(cat /etc/installer/scripts.txt | awk '{print $1}' | grep $script)
if [ "$scriptcheck" ]
then
echo -e "$cyanClaro""Installing Script: $script"
wget -q https://raw.githubusercontent.com/BadGuy552/scripts/master/$script
rm /bin/$script  1>/dev/null 2>/dev/null
rm /usr/bin/$script  1>/dev/null 2>/dev/null
mv $script /bin/
chmod a+x /bin/$script
wget -q https://raw.githubusercontent.com/BadGuy552/scripts/master/table
rm /bin/table  1>/dev/null 2>/dev/null
rm /usr/bin/table  1>/dev/null 2>/dev/null
mv table /bin/
chmod a+x /bin/table
echo -e "$cyanClaro""Script $fim $vermelho""$script""$fim""$cyanClaro Installed Sucefully!"
echo -e "$cyanClaro""Execute With this command: $fim""$verde$script""$fim"
else
echo -e "$cyanClaro""This Script: $script Not Exists!$fim"
exit
fi
else
echo -e "$cyanClaro""You Not Inserted a name, Try Again$fim"
exit
fi
