#!/bin/bash

if [ ! "$BASH" ]
then
echo "Este script foi feito para funcionar com o bash
Reiniciando o Script usando BASH em 3 segundos..."
sleep 3
bash $0 $@
exit $?
fi
clear
menu="\033[41;1;37m"
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0m"

echo -e "$menu
			LINK EXTRACTOR v0.1b			$fim"
if [ ! "$1" ]
then
echo -e "$vermelho
Por favor Insira uma lista com os sites para terem os links extraidos...$fim"
exit 1
fi
if [ -f "$1" ]
then
echo "Capturando Links..."

if [ "$OUTPUT_LE" ]
then
echo "OUTPUT: $OUTPUT_LE"
OUTPUT=$OUTPUT_LE
fi

while read sites
do
echo -e "$cyanClaro
Capturando links do site $sites"..."$fim"
links=$(curl $sites -L --silent | grep href | awk '{print $2}' | grep href= | awk -F "=" '{print $2}' | cut -d'"' -f 2 | grep -v javascript | grep -v '#')
echo -e "\t$azulClaro
$sites$fim"
echo "$links"
if [ "$OUTPUT" ]
then
echo "$links" >> $OUTPUT
fi
done < $1
echo -e "$verde
Fim!$fim"
exit 0
else
echo -e "$vermelho
Arquivo $1 não encontrado!$fim"
exit 1
fi


