#!/bin/bash
if [ ! "$BASH" ]
then
echo "Este script foi feito para funcionar com o bash
Reiniciando o Script usando BASH em 3 segundos..."
sleep 3
bash $0 $@
exit $?
fi
clear
menu="\033[41;1;37m"
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0m"

echo -e "$menu			OPENSSH-SERVER-5.9p1 Instalador			$fim"
sleep 1
echo -e "$azulClaro
Este é um script EXPERIMENTAL feito para instalar a versão 5.9p1 do openssh-server.
Ele foi feito para sistemas Debian e variados (como Ubuntu, etc..)
Este script não tem garantias de funcionamento, portanto esteja ciente dos riscos que podem vir a ocorrer em seu sistema.$fim"
read -p "Pressione qualquer tecla para continuar..." continuar
echo -e "$vermelho
Este script vai fazer testes de compatibilidade em seu sistema para prevenir futuros erros e verificar a compatibilidade...$fim"
read -p "Pressione qualquer tecla para continuar..." continuar
echo -e "$cyanClaro
Executando testes...$fim"
function aptTest {
test=$(which apt-get)
if [ "$test" ]
then
echo "OK"
else
echo "FAIL"
fi
}
function dpkgTest {
test=$(which dpkg)
if [ "$test" ]
then
echo "OK"
else
echo "FAIL"
fi
}
function wgetTest {
test=$(which wget)
if [ "$test" ]
then
echo "OK"
else
echo "FAIL"
fi
}
function ArchTest {
echo -e "$vermelho
Sua arquitetura: $(arch)$fim"
if [[ "$(arch)" != "i386" && "$(arch)" != "x86_64" ]]
then
echo "Sua arquitetura ainda não é suportada por este script."
exit 1
fi
if [ "$(arch)" = "x86_64" ]
then
arch=amd64
else
arch=i386
fi
}

if [ aptTest = "FAIL" ]
then
echo -e "$vermelho
O pacote apt-get não esta presente em seu sistema, e ele é necessario para o funcionamento deste script.$fim"
exit 1
else
echo -e "$cyanClaro
apt-get OK$fim"
fi
if [ dpkgTest = "FAIL" ]
then
echo -e "$vermelho
O pacote dpkg não esta presente em seu sistema, e ele é necessario para o funcionamento deste script.$fim"
exit 1
else
echo -e "$cyanClaro
dpkg OK$fim"
fi
if [ wgetTest = "FAIL" ]
then
echo -e "$vermelho
O pacote wget não esta presente em seu sistema, e ele é necessario para o funcionamento deste script.$fim"
exit 1
else
echo -e "$cyanClaro
wget OK$fim"
fi
ArchTest
echo -e "$cyanClaro
Dependencias verificadas.$fim"

sleep 1

echo -e "$vermelho
Baixando openssh-server5.9p1$fim"
mkdir openssh-server-5.9p1
wget -q http://security.ubuntu.com/ubuntu/pool/main/o/openssh/openssh-server_5.9p1-5ubuntu1.10_$arch.deb -O openssh-server-5.9p1/openssh-server_$arch.deb
echo -e "$vermelho
Baixando openssh-client5.9p1$fim"
wget -q http://security.ubuntu.com/ubuntu/pool/main/o/openssh/openssh-client_5.9p1-5ubuntu1.10_$arch.deb -O openssh-server-5.9p1/openssh-client_$arch.deb
echo -e "$vermelho
Instalando upstart-job$fim"
apt-get update 1>/dev/null 2>/dev/null
apt-get install upstart-job -y 1>/dev/null 2>/dev/null
echo -e "$vermelho
Desinstalando openssh-sftp-server$fim"
apt-get purge openssh-sftp-server -y 1>/dev/null 2>/dev/null
echo -e "$vermelho
Instalando openssh5.9p1$fim"
if [ "$1" = "--verbose" ]
then
cd openssh-server-5.9p1 && dpkg -i * 
else
cd openssh-server-5.9p1 && dpkg -i * 1>/dev/null 2>/dev/null
fi
cd ..
rm -rf openssh-server-5.9p1
echo -e "$menu
openssh-server5.9p1 e openssh-client5.9p1 Instalados.$fim"
echo "By: telegram.me/badguy3
Canal: telegram.me/badguy_channel
Github: github.com/badguy552"
exit 0
