#!/bin/bash
echo "Checking for Updates...."
update=$(curl -H 'Cache-Control: no-cache' -s https://raw.githubusercontent.com/BadGuy552/scripts/master/v | grep proxy | awk '{print $2}')
version=2
if [ "$update" -gt "$version" ]
then
echo "Updating Script proxy..."
wget -q https://raw.githubusercontent.com/BadGuy552/scripts/master/proxy
rm /bin/proxy 1>/dev/null 2>/dev/null
mv proxy /bin/ 1>/dev/null 2>/dev/null
chmod a+x /bin/proxy 1>/dev/null 2>/dev/null
echo "Run Script Again!"
exit 1
fi
clear

# Copyright BadGuy
# SSH TLS

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

if [ "$1" = ""  ]
then
echo -e "			\033[41;1;37m Proxy Checker \033[0m "	
sleep 1
echo -e " Forma de USO: "
echo -e "$0 ARQUIVO COM A LISTA DE PROXYS.    "
echo -e " Exemplo:"
echo -e "$0 proxys.txt    "
exit 0
fi


echo -e "			\033[41;1;37m Proxy Checker \033[0m "	

lista=$1

sleep 1

echo -e "\033[44;1;37m Testando....     \033[0m "
while read proxys
do
case "$(curl --proxy $proxys -s --max-time 0.5 -I http://google.com | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
  [23]) echo -e "Proxy: $proxys [$verde OK \033[0m]" && echo -e "Proxy: $proxys [$verde OK \033[0m]" '#BadGuy-Proxy-checker' >> work.txt;;
  5) echo -e "Proxy: $proxys [$vermelho Erro \033[0m]" && echo -e "Proxy: $proxys [$vermelho Erro \033[0m]" '#BadGuy-Proxy-checker' >> fail.txt;;
  *) echo -e "Proxy: $proxys [$vermelho Não Funcionando. \033[0m]" && echo -e "Proxy: $proxys [$vermelho Não Funcionando. \033[0m]" '#BadGuy-Proxy-checker' >> fail.txt;;
esac

done < $lista

echo -e "Você pode ver a lista de Proxys Funcionais no arquivo $verde work.txt \033[0m"
echo -e "BadGuy"
echo "SSH TLS"
echo "Raphael Frajuca"

exit 0
