#!/bin/bash

if [ ! "$BASH" ]
then
echo "Este script foi feito para funcionar com o bash
Reiniciando o Script usando BASH em 3 segundos..."
sleep 3
bash $0 $@
exit $?
fi
clear
menu="\033[41;1;37m"
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0m"

echo -e "$menu
			SQUID v4 Compiler			$fim"
			
echo -e "$vermelho
Este é um Script EXPERIMENTAL para compilar e instalar a source code do squid v4$fim"
echo -e "$vermelho
Neste script não ha NENHUMA garantia de funcionamento ou suporte do ator, esteja ciente dos riscos.$fim"
read -p "Aperte Enter para continuar..."

echo -e "$cyanClaro
Instalando Pré requisitos....$fim"

apt-get update 1>/dev/null 2>/dev/null
apt-get install git-core gnupg flex bison gperf build-essential \
  zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
  lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
  libgl1-mesa-dev libxml2-utils xsltproc unzip gcc g++ bc make wget -y 1>/dev/null 2>/dev/null
  
echo -e "$cyanClaro
Baixando Source Code do SQUID....$fim"

wget https://fourdots.com/mirror/squid/archive/4/squid-4.0.17.tar.gz -q
if [ -f squid-4.0.17.tar.gz ]
then
echo -e "$verde
Download Completo!$fim"
else
echo -e "$vermelho
Algum erro ocorreu no download!$fim"
exit 1
fi
mkdir squid
mv squid-4.0.17.tar.gz squid
sleep 3
echo -e "$cyanClaro
Extraindo SQUID....$fim"
sleep 3
cd squid && tar -xvf squid-4.0.17.tar.gz

echo -e "$cyanClaro
Apartir de Agora, iniciara o processo de compilação do SQUID, dependendo de seu hardware este processo deve demorar.$fim"
read -p "Aperte Enter para continuar..."

echo -e "$cyanClaro
Configurando build...$fim"
cd squid-4.0.17 && ./configure --prefix=/usr \
--localstatedir=/var \
--libexecdir=${prefix}/lib/squid \
--datadir=${prefix}/share/squid \
--sysconfdir=/etc/squid \
--with-default-user=proxy \
--with-logdir=/var/log/squid \
--with-pidfile=/var/run/squid.pid

echo -e "$cyanClaro
Iniciando Compilação...$fim"
sleep 3
make
echo -e "$cyanClaro
Instalando SQUID...$fim"
make install

echo -e "$cyanClaro
Baixando SCRIPT de inicialização do squid...$fim"
apt-get purge squid squid3 -y 1>/dev/null 2>/dev/null
wget -q https://raw.githubusercontent.com/BadGuy552/scripts/master/squid-init
mv squid-init /etc/init.d/squid
chmod a+x /etc/init.d/squid
echo -e "$verde
Todos os precessos foram finalizados.$fim"
squid -v | grep "Squid Cache"
exit 0
