#!/bin/bash
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
versao=1.6.2
if [ -d /etc/users/ ]
then
echo "Continuando.."
sleep 1
clear
else
echo "Este é o Primeiro USO"
mkdir /etc/users/
sleep 1
fi
while true
do
clear
echo -e "                       \033[41;1;37m SSHLIMITER $versao \033[0m "
awk -F : '$3 >= 1000 { print $1 }' /etc/passwd |grep -v "nobody" > /etc/users/users.txt
while read users
do
if [ "$1" ]
then
limite=$1
else
limite=1
fi
count=$(ps x | grep $users | grep sshd | grep -v grep | grep -v pts | wc -l)
proc=$(ps x | grep $users | grep sshd | grep -v grep | grep -v pts | awk -F " " '{print $1}')
echo -e "..................................................."
echo -e "    $verde$users\033[0m $count/$verde$limite\033[0m"
if [ "$count" -gt "$limite" ]
then
echo -e "\033[44;1;37m Desconectando Usuarios:     \033[0m "
sleep 0.5s
kill $proc
echo "IDS:
$proc
Desconectados!
"
fi
done < /etc/users/users.txt
echo -e "..................................................."
sleep 2.5s
clear
done
